# This file runs CI/CD pipelines on GitLab
# it has been setup to provide testing on a mirror
default:
  image: python:3.10.11
  tags: 
    # Ensure that our pipelines only run on aws runners
    - aws

stages:
  - test

unit-test:
  stage: test
  when: manual
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install --upgrade pip
    - pip install .[test]
    - pytest tests/unit
    - pylint target_snowflake
